# DEV ?????????
base.url=https://jsonplaceholder.typicode.com
browser=chrome
timeout.seconds=5
log.level=DEBUG
headless=false
# Docker ?????????
docker.enabled=false
docker.selenium.url=http://localhost:4444/wd/hub